# Generated by Django 2.2.7 on 2020-03-02 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smain_2', '0002_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='video',
            name='username',
            field=models.CharField(max_length=500),
        ),
    ]
