# Generated by Django 2.2.7 on 2020-03-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smain_2', '0003_auto_20200302_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='stream_key',
            field=models.CharField(max_length=500),
        ),
    ]
