# Generated by Django 2.2.7 on 2020-03-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smain_2', '0006_auto_20200303_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.URLField(default='NULL', max_length=500),
        ),
    ]
