# Generated by Django 2.2.7 on 2020-03-03 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smain_2', '0008_video_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_title',
            field=models.CharField(default='Untitled', max_length=500),
        ),
    ]
