# Generated by Django 2.2.7 on 2020-03-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smain_2', '0009_video_video_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
